### ISSUE TITLE
`finetuning_data`✅, `TEST_INDICES`✅, and `training video`❓ Release

### ISSUE THREAD

**Issue by chunhuizng** [chuanyangjin/MMToM-QA#2]
Could you release the `TEST_INDICES` and `finetuning_data` used in `graph_utils.py` and `generate_finetuning_dataset.py`? 

Thanks!

**Comment by chuanyangjin** [comment]
Thanks for pointing this out! We've released the TEST_INDICES in graph_utils.py. We will release the finetuning_data soon.

**Comment by chunhuizng** [comment]
> Thanks for pointing this out! We've released the TEST_INDICES in graph_utils.py. We will release the finetuning_data soon.

Thank you and very look forward to it!

**Comment by chunhuizng** [comment]
Thanks for kindly sharing the training_set.zip!

By the way, could you also share the video data in the `training_set.zip`? 

The current version includes `belief_{num}.pik, camera_data_{num}.pik, graph_{num}.pik, init_graph.pik, instanace_colors.pik, env_info.pik, actions.pik`. 

if `training_set.zip` can include the vision data, such as video-related RGB and depth file, it would be helpful to reproduce and conduct multimodal training/finetuning experiments (I guess the path is in `task_{episode}/script/0/`). 

Thanks!
