### ISSUE TITLE
✅ `multimodal_representations.json` extracted from `text_parsing.py`

### ISSUE THREAD

**Issue by chunhuizng** [chuanyangjin/MMToM-QA#3]
Hi Chuanyang,

Could you release the extracted `multimodal_representations.json` from `text_parsing.py`?

I found it would be directly useful for reproducing the claimed inference results of BIP-ALM reported in the MMToM-QA paper, and it seems that this .json file is not currently released in the repo for test evaluation.

Thank you very much!

P.S. If the extracted `.json` files from `python visual_perception.py --benchmark_video_path videos` could also be released, I would highly appreciate it.

**Comment by chuanyangjin** [comment]
Hi Chunhui, thank you for your interest in our paper! We have released the requested files.

**Comment by chunhuizng** [comment]
> Hi Chunhui, thank you for your interest in our paper! We have released the requested files.

Thank you very much, Chuanyang! They are super helpful.

I would also like to share some additional `.json` files used in the middle process: [Google Drive folder](https://drive.google.com/drive/folders/1G1fADmM5CN0IG407AEuTfTs-vm9sW6gJ?usp=sharing) in case anyone wants to use them.
