### ISSUE TITLE
✅ `inference_raw.json` for `BIP-ALM` test evaluation in reproducing

### ISSUE THREAD

**Issue by chunhuizng** [chuanyangjin/MMToM-QA#4]
Hi Chuanyang,

Could you release the `inference_raw.json` file used in `text_parsing.py` for test evaluation? 

To reproduce the  _BIP-ALM_method test, we need the `multimodal_representations.json` file. However, generating this file requires running `text_parsing.py` with `inference_raw.json`, which is not currently available in the repo (and also lacks instructions on how to create it).

If the `inference_raw.json` file can be released (or, more straightforwardly, if the final evaluation test data `multimodal_representations.json` for _BIP-ALM_ can be released), it will enable successfully reproducing the test evaluation of the proposed  _BIP-ALM_ method. This would help to enhance the impact and reproducibility of this smart paper within the community. 

Thank you very much!

**Comment by chuanyangjin** [comment]
We have released the requested files. You can now find them in the folder "files" for use in reproducing our results. Thank you for bringing this to our attention!

**Comment by chunhuizng** [comment]
> We have released the requested files. You can now find them in the folder "files" for use in reproducing our results. Thank you for bringing this to our attention!

Thank you very much, Chuanyang! They are super helpful. 

I would also like to share some additional `.json` files used in the middle process: [Google Drive folder](https://drive.google.com/drive/folders/1G1fADmM5CN0IG407AEuTfTs-vm9sW6gJ?usp=sharing) in case anyone wants to use them.
